### ISSUE TITLE
Not working with Github CI but does with Gitlab ? 

### ISSUE THREAD

**Issue by Mikaleb** [makenotion/notion-sdk-js#322]
Report bugs here only for the Node JavaScript library.

If you're having problems using Notion's API, or have any other feedback about the API including feature requests for the JavaScript library, please email support at developers@makenotion.com.

**Describe the bug**
Tried running a Github CI with a simple `npm i` & `npm start` to go make the calls to notion api but I always get : 

```bash
@notionhq/client warn: request fail { code: 'unauthorized', message: 'API token is invalid.' }
APIResponseError: API token is invalid.
```

**To Reproduce**
Node version:
Notion JS library version: v16

the yaml workflow file : 

```yml
name: Node.js CI

env: 
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}

on:
  schedule:
    - cron: '30 7 * * *' # At 07:30 everyday
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run start --if-present
```

**Expected behavior**

Call api to do whatever i have to using environment variables I passed into Github project's secrets

**Screenshots**

**Additional context**
[Repo with code](https://github.com/Mikaleb/Bing-Daily-Notion-cover)
